"""
templates — draft contract bodies
=================================

Plain-text templates with {curly} placeholders. Intentionally conservative
and disclosure-forward (equitable interest, assignment, inspection/financing
contingencies, attorney review). NOT legal advice.
"""

from __future__ import annotations

BANNER = (
    "================================================================\n"
    " DRAFT — NOT LEGAL ADVICE — ATTORNEY REVIEW REQUIRED BEFORE USE\n"
    " Generated by the wholesale platform on {generated}.\n"
    " A licensed real-estate attorney in {state} must review and adapt\n"
    " this document. Pre-foreclosure / distressed transactions are\n"
    " separately regulated (equity-purchaser & foreclosure-consultant\n"
    " laws) and may require additional disclosures, notices, and a\n"
    " statutory right of rescission.\n"
    "================================================================\n"
)

# --- Purchase & Sale Agreement (we buy from the seller) ---------------------
PURCHASE_AGREEMENT = """{banner}
REAL ESTATE PURCHASE AND SALE AGREEMENT (ASSIGNABLE)

Effective Date: {generated}

1. PARTIES
   Buyer: {buyer_entity} ("Buyer"), or its assigns.
   Seller: {seller_name} ("Seller").

2. PROPERTY
   The real property located at {address}, {city}, {state} {zip}
   (the "Property"), together with all improvements and fixtures.

3. PURCHASE PRICE
   Total Purchase Price: ${contract_price:,} USD.
   Earnest Money Deposit: ${earnest:,} USD, held in escrow.

4. ASSIGNMENT
   This Agreement and Buyer's rights hereunder are freely ASSIGNABLE by
   Buyer to a third party. Buyer holds an equitable interest in the
   Property upon execution. Buyer is acting as a principal/assignor and
   is NOT acting as a licensed real-estate broker or agent for Seller.

5. CLOSING
   Closing on or before {closing_days} days from the Effective Date, at a
   title company or closing attorney selected by Buyer. Seller to convey
   marketable title by general warranty deed, free of liens except as
   agreed.

6. CONTINGENCIES
   (a) Inspection: Buyer may inspect and may terminate for any reason
       within {inspection_days} days, with full refund of the deposit.
   (b) Title: subject to clear/insurable title.
   (c) Property sold STRICTLY AS-IS; Seller makes no repairs.

7. DISCLOSURES
   Seller acknowledges Buyer intends to RESELL or ASSIGN this contract for
   a profit, potentially for more than the Purchase Price. Seller enters
   into this Agreement freely and may seek independent legal counsel.

8. DEFAULT / REMEDIES; GOVERNING LAW
   Governed by the laws of {state}. [Attorney to complete remedies,
   default, dispute-resolution, and any state-mandated clauses.]

Seller: ______________________________  Date: ____________
{seller_name}

Buyer:  ______________________________  Date: ____________
{buyer_entity}, by authorized signatory
"""

# --- Assignment of Contract (we sell the contract to an investor) -----------
ASSIGNMENT_AGREEMENT = """{banner}
ASSIGNMENT OF REAL ESTATE PURCHASE AND SALE AGREEMENT

Effective Date: {generated}

1. PARTIES
   Assignor: {buyer_entity} ("Assignor").
   Assignee: {assignee} ("Assignee").

2. UNDERLYING AGREEMENT
   That certain Purchase and Sale Agreement dated {generated} between
   Assignor (as Buyer) and {seller_name} (as Seller) for the property at
   {address}, {city}, {state} {zip} (the "Agreement"), purchase price
   ${contract_price:,}.

3. ASSIGNMENT & FEE
   Assignor assigns all right, title, and interest in the Agreement to
   Assignee. In consideration, Assignee pays Assignor a non-refundable
   ASSIGNMENT FEE of ${assignment_fee:,} USD, due upon execution and
   payable at or before closing of the Agreement.

4. ASSUMPTION
   Assignee assumes all of Assignor's obligations under the Agreement and
   agrees to perform and close per its terms. Assignor makes no warranty
   as to the condition of the Property; Assignee has performed its own
   due diligence.

5. CLOSING
   Closing per the Agreement. The Assignment Fee is disclosed on the
   closing/settlement statement.

6. GOVERNING LAW
   Governed by the laws of {state}. [Attorney to complete.]

Assignor: ____________________________  Date: ____________
{buyer_entity}

Assignee: ____________________________  Date: ____________
{assignee}
"""
